#ifndef CARPROJECT_LIB_GUI_INCLUDE_WINDOWCOORDINATS_H_
#define CARPROJECT_LIB_GUI_INCLUDE_WINDOWCOORDINATS_H_

class windowCoordinats {
protected:
    static int x_, y_;
};


#endif //CARPROJECT_LIB_GUI_INCLUDE_WINDOWCOORDINATS_H_
